[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools >= 64.0",
    "cmake >= 3.24",
    "wheel",
    "jupyterlab (>=3.0.6, <3.6.0)",
    "conan ~= 2.4.1",
    "cython ~= 3.0.10",
    "numpy"
]
